name: Permissions Sync using cncf/sheriff
jobs:
  perm-sync:
    permissions:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: us.gcr.io/cncf-slack-infra/sheriff/sheriff:cncf-slack-plugin
      env:
        PERMISSIONS_FILE_ORG: cncf
        SHERIFF_HOST_URL: 'https://sheriff-ajrw3kq6ta-uc.a.run.app'
        SHERIFF_PLUGINS: cncfSlack
        PERMISSIONS_FILE_REPO: people
        SHERIFF_IMPORTANT_BRANCH: main

        GSUITE_CREDENTIALS: ${{ secrets.gsuite_creds }}
        SHERIFF_GITHUB_APP_CREDS: ${{ secrets.sheriff_github_app-creds }}
        GITHUB_WEBHOOK_SECRET: ${{ secrets.sheriff_github_secret }}
        SLACK_TOKEN: ${{ secrets.sheriff_slack_oauth_token }}
        SLACK_WEBHOOK_URL: ${{ secrets.sheriff_slack_webhook_url }}
      port:
